services:
  reloomate-api:
    build: .
    container_name: reloomate-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
